name: Jolly Blog
description: >-
  Student Reverse Engineer and Malware Analyst
  
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: Jollycistaken
  instagram:
  linkedin:
  pinterest:
  rss: 
  twitter: Jollycistaken
  stackoverflow: 
  youtube: 
  googleplus:

disqus:
google_analytics:
url:
baseurl: ""
permalink: /:title/
version: v1.2.0
sass:
  style: :expanded
  
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME